i8_core_endpoint: https://api.investoreight.com
app:
  port: 8050
  debug: false
metrics:
  similarity_threshold: 0.75
cache:
  age: 48 # Hours
styles:
  plot:
    default:
      paper_bgcolor: "#F8F9F9"
      plot_bgcolor: "#E5E8E8"
  table:
    default:
      header:
        color: "magenta"
        bold: true
      row:
        color: "white"
      alternate_row:
        color: "cyan"
      show_lines: false
    company_compare:
      alternate_row:
        color: cyan
      header:
        bold: true
        color: magenta
      row:
        color: white
      show_lines: false
    metrics_historical:
      alternate_row:
        color: cyan
      header:
        bold: true
        color: magenta
      row:
        color: white
      show_lines: false
  terminal:
    command:
      color: "magenta"
  xlsx:
    default:
      header:
        bold: True
        fg_color: "#00B191"
        border: 1
        align: "center"
        valign: "vcenter"
      metric:
        bold: True
        text_wrap: True
        valign: "top"
    company:
      column:
        num_format: "#,##0.00"
        valign: "vcenter"
        text_wrap: True
    financials:
      column:
        num_format: "#,##0.00"
        valign: "vcenter"
        text_wrap: True
    price:
      column:
        num_format: "#,##0.00"
metric_view:
  watchlist_summary:
    metrics: "company_name,stock_exchange,price.r,change,52_week_low,52_week_high,marketcap"
  watchlist_financials:
    metrics: "total_revenue,net_income,basic_eps,net_cash_from_operating_activities,total_assets,total_liabilities"
commands:
  company_compare:
      metric_groups:
        - name: "Summary"
          metrics: "company_name,sector,industry_group,price,change,marketcap,pe_ratio_ttm"
        - name: "Financials"
          metrics: "return_1w,return_1m,return_3m,return_6m,return_ytd,return_1y,return_2y,return_5y"
        - name: "Performance"
          metrics: "pe_ratio_ttm,current_ratio,quick_ratio,price_to_book,revenue_growth,dividend_yield,roe"
        - name: "Key Ratios"
          metrics: pe_ratio_ttm,current_ratio,quick_ratio,price_to_book,revenue_growth,dividend_yield,roe
  screen_gainers:
      metrics: "company_name,price,change"
  screen_losers:
      metrics: "company_name,price,change"
