name: Publish i8 Terminal Doc to ghpages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64

      - name: Build documentation & publish to ghpages
        run: |
          pip3 install mkdocs
          pip3 install mkdocs-click
          pip3 install mkdocs-material
          pip3 install i8-terminal
          mkdocs gh-deploy --force --clean --verbose