name: Test and Publish i8 Terminal to PyPi
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-v1-test
          restore-keys: ${{ runner.os }}-v1-test

      - run: pip3 install -r requirements-dev.txt
      - run: pyflakes i8_terminal/
      - run: black --check i8_terminal/
      - run: isort --check i8_terminal/
      - run: mypy i8_terminal/

  publish_pypi:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-v1-test
          restore-keys: ${{ runner.os }}-v1-test

      - name: Build package & publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          pip3 install twine==4.0.0
          python setup.py sdist
          twine upload dist/i8-terminal-$(python setup.py -V).tar.gz

  publish_ghdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64

      - name: Build documentation & publish to ghpages
        run: |
          pip3 install mkdocs
          pip3 install mkdocs-click
          pip3 install mkdocs-material
          mkdocs gh-deploy --force --clean --verbose
